app:
    resource: "@AppBundle/Controller/"
    type:     annotation

redirect_home:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:Redirect
    route: book_list
    permanent: true

book_list:
  path: /books
  defaults:
    _controller: AppBundle:Book:listbooks

book_new:
  path: /books/new
  defaults:
    _controller: AppBundle:Book:new
