app:
    resource: "@AppBundle/Controller/"
    type:     annotation

redirect_home:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:Redirect
    route: book_list
    permanent: true

book_list:
  path: /books
  defaults:
    _controller: AppBundle:Book:listBooks

book_new:
  path: /books/new
  defaults:
    _controller: AppBundle:Book:new

book_view:
  path: /books/view/{id}
  defaults:
    _controller: AppBundle:Book:viewBook

book_edit:
  path: /books/edit/{id}
  defaults:
    _controller: AppBundle:Book:editBook

book_load_fixtures:
  path: /books/fixtures-load
  defaults:
    _controller: AppBundle:Book:loadBookFixtures
