AppBundle\Entity\Book:
    properties:
        title:
            - NotBlank:
                groups: [creation]
        author:
            - NotBlank:
                groups: [creation]
        isbn:
            - NotBlank:
                groups: [creation]